/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446xx.h"


#define PLLR (2<<28)
#define PLLQ (6<<24)
#define PLLSRC (0<<22)
#define PLLP  (0b00<<16)
#define PLLN  (288<<6)
#define PLLM  (16<<0)

#define HSION (1U<<0)
#define HSIRDY (1U<<1)


int main(void)
{

	/*Process to configure PLL CLOCK AT 144MHz
	 * 1. Enable HSI clock
	 * 2. Select HSI clock as system clock
	 * 3. Turning off PLL
	 * 4. Configure RCC_PLLCFGR with all parameters (M,N,P,Q,R,SRC), It's recommended to use STM32CubeIDE to calculate this parameters
	 * 5. Turning on PLL
	 * 6. Configure FLASH_ACR register
	 * 7. Configure RCC_CFGR register
	 * */


	RCC->CR |= HSION;//Enable HSI clock
	while((RCC->CR & HSIRDY)==0);//Wait until HSRDY is set

	RCC->CFGR &= ~(1U<<0);//Select HSI as System Clock
	RCC->CFGR &= ~(1U<<1);//Select HSI as System Clock
	while((RCC->CFGR & (0b00<<2))!=0b00);//Wait until HSI is selected as System Clock

	RCC->CR &=~(1U<<24); //Turning off PLL
	while((RCC->CR & (1U<<25)));//Wait until PLLRDY is reset (unlocked)

	//The following parameters produce a PLL clock frequency of 144MHz
	RCC->PLLCFGR = 0; // Clear PLLCFGR register
	RCC->PLLCFGR |= PLLR; //Set 2 in PLLR bits
	RCC->PLLCFGR |= PLLQ; //Set 6 in PLLQ bits
	RCC->PLLCFGR |= PLLSRC; //Set 0 in PLLSRC bit this means that HSI clock is selected as PLL and PLLI2S entry clock source
	RCC->PLLCFGR |= PLLP; //Set 00 in PLLP bits this means PLLP=2
	RCC->PLLCFGR |= PLLN; //Set 288 in PLLN bits
	RCC->PLLCFGR |= PLLM; //Set 16 in PLLM bits


	RCC->CR |= (1<<24); //Turning on PLL
	while(!(RCC->CR & (1<<25)));//Wait until PLLRDY is set (locked)

	//WARNING!!!
	//Please read "Relation between CPU clock frequency and Flash memory read time" in the reference manual to understand why it's important the following settings
	FLASH->ACR |= (4<<0);//Configure 4 WS (Wait States), this means the ratio of the CPU clock period to the Flash Memory access time
	FLASH->ACR |= (1U<<8);


	RCC->CFGR |= (0<<4); //AHB prescaler System clock not divided
	RCC->CFGR |= (5<<10); //APB1 clock divided by 4
	RCC->CFGR |= (4<<13); //APB2 clock divided by 2
	RCC->CFGR |= (2<<0); //Select PLL as the System Clock
	while ((RCC->CFGR & (3 << 2)) != (2 << 2));//Wait until PLL system Clock is ready


	RCC->APB2ENR|= (1<<0);
	TIM1->CR1 |= (1U<<0);
	TIM1->PSC = 14400;
	TIM1->ARR = 100;


	while(1){


		}


}
